### ISSUE TITLE
Can't download pre-trained models

### ISSUE THREAD

**Issue by daidedou** [lpj0/MWCNN#6]
Hi, 
Since you've uploaded pretrained weights, it seems that Baidu changed its politics. It seems that now you need a Baidu account for download the weights+install baidu disk. Isn't it possible to put them on a google drive/dropbox/whatever?
Thank you very much for releasing the code!

**Comment by lpj0** [comment]
OK, I've uploaded to google drive and shared it. (https://drive.google.com/drive/folders/1GX_NQfG1-QHdfgmV8Axl1ZjlDsHUEAUV?usp=sharing)

**Comment by daidedou** [comment]
Thank you very much!
